import Login from '@/components/Login'
import { useSession } from 'next-auth/react'
import Head from 'next/head'

export default function Home() {

const {data: session} = useSession()
// handle login 
if (!session) return <Login />;


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        HomePage
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context)

  return {
    props: {
      session,
    },
  };
}
